spring.application.name=auth-service

server.port=${AUTH_SERVICE_PORT:8081}

# Load .env file
spring.config.import=optional:file:.env[.properties]

# PostgreSQL
spring.datasource.url=${AUTH_DB_URL}
spring.datasource.username=${AUTH_DB_USERNAME}
spring.datasource.password=${AUTH_DB_PASSWORD}

# JPA
spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO:update}
spring.jpa.show-sql=${JPA_SHOW_SQL:true}
spring.jpa.properties.hibernate.format_sql=${JPA_FORMAT_SQL:true}

# Eureka
eureka.client.service-url.defaultZone=${EUREKA_DEFAULT_ZONE:http://localhost:8761/eureka/}
eureka.instance.prefer-ip-address=true

# Actuator
management.endpoints.web.exposure.include=*

# GOOGLE OAUTH2
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=openid,profile,email

# FRONTEND
app.frontend-url=${APP_FRONTEND_URL:http://localhost:5173}