spring.application.name=gateway-service

server.port=${PORT:8080}

# Eureka
eureka.client.service-url.defaultZone=${EUREKA_DEFAULT_ZONE:http://localhost:8761/eureka/}
eureka.instance.prefer-ip-address=true

# Actuator
management.endpoints.web.exposure.include=${ACTUATOR_EXPOSURE:*}

# spring.cloud.gateway.routes[0].id=auth-service
# spring.cloud.gateway.routes[0].uri=lb://AUTH-SERVICE
# spring.cloud.gateway.routes[0].predicates[0]=Path=/api/auth/**
