spring.application.name=payment-service

server.port=8086

spring.datasource.url=jdbc:postgresql://localhost:5432/baentech_payment_db
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

management.endpoints.web.exposure.include=*


# XENDIT
xendit.secret-key= xnd_public_development_JSKFRh9kTLOe07Z7_R6PPwz9gKNxWlQe8WnXnnOGzQepPw1ZE1zgfblfK0eA5ES
xendit.callback-token=SqPGrebJztaLWgGHDLz2RBM9eiLnQOad8eOjMiatizrBHAxw
xendit.invoice-url=https://api.xendit.co/v2/invoices

# FRONTEND
app.frontend-url=http://localhost:5173

# INTERNAL SERVICE TOKEN
internal.api-key=baentech-internal-secret-2026
order.service.url=http://localhost:8085