spring.application.name=payment-service

server.port=${PORT:${PAYMENT_SERVICE_PORT:8086}}
# Load .env file
spring.config.import=optional:file:.env[.properties]

# PostgreSQL
spring.datasource.url=${PAYMENT_DB_URL}
spring.datasource.username=${PAYMENT_DB_USERNAME}
spring.datasource.password=${PAYMENT_DB_PASSWORD}

# JPA
spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO:update}
spring.jpa.show-sql=${JPA_SHOW_SQL:true}
spring.jpa.properties.hibernate.format_sql=${JPA_FORMAT_SQL:true}

# Eureka
eureka.client.service-url.defaultZone=${EUREKA_DEFAULT_ZONE:http://localhost:8761/eureka/}
eureka.instance.prefer-ip-address=true

# Actuator
management.endpoints.web.exposure.include=${ACTUATOR_EXPOSURE:*}

# XENDIT
xendit.secret-key=${XENDIT_SECRET_KEY}
xendit.callback-token=${XENDIT_CALLBACK_TOKEN}
xendit.invoice-url=${XENDIT_INVOICE_URL:https://api.xendit.co/v2/invoices}

# FRONTEND
app.frontend-url=${APP_FRONTEND_URL:http://localhost:5173}

# INTERNAL SERVICE TOKEN
internal.api-key=${INTERNAL_API_KEY}
order.service.url=${ORDER_SERVICE_URL:http://ORDER-SERVICE}